# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'services.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\x12\x0eproto_services\"\x1e\n\x0eProductRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"C\n\x0fProductResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\"<\n\x0b\x43hatMessage\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04room\x18\x03 \x01(\t2_\n\x0eProductService\x12M\n\nGetProduct\x12\x1e.proto_services.ProductRequest\x1a\x1f.proto_services.ProductResponse2S\n\x0b\x43hatService\x12\x44\n\x04\x43hat\x12\x1b.proto_services.ChatMessage\x1a\x1b.proto_services.ChatMessage(\x01\x30\x01\x42-\n\x1a\x63om.example.proto.servicesB\rServicesProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.example.proto.servicesB\rServicesProtoP\001'
  _globals['_PRODUCTREQUEST']._serialized_start=34
  _globals['_PRODUCTREQUEST']._serialized_end=64
  _globals['_PRODUCTRESPONSE']._serialized_start=66
  _globals['_PRODUCTRESPONSE']._serialized_end=133
  _globals['_CHATMESSAGE']._serialized_start=135
  _globals['_CHATMESSAGE']._serialized_end=195
  _globals['_PRODUCTSERVICE']._serialized_start=197
  _globals['_PRODUCTSERVICE']._serialized_end=292
  _globals['_CHATSERVICE']._serialized_start=294
  _globals['_CHATSERVICE']._serialized_end=377
# @@protoc_insertion_point(module_scope)
