/*
 * This source file was generated by the Gradle 'init' task
 */
package grpc_trabajo;
import java.io.IOException;

public class App {
    public static void main(String[] args) throws IOException, InterruptedException { //Empieza el servidor definiendo las configuraciones en AppConfig
        grpc_trabajo.bootstrap.ServerBootstrap server = new grpc_trabajo.bootstrap.ServerBootstrap();
        grpc_trabajo.config.AppConfig config = new grpc_trabajo.config.AppConfig();
        server.start(config);
    }
}
